// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.Data;

#nullable disable

namespace SalesManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403110623_Added FK Relation in ProductRecipeDetail")]
    partial class AddedFKRelationinProductRecipeDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.Models.CategoryRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CategoryRanges");
                });

            modelBuilder.Entity("SalesManagement.Models.KOT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BILLED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BILLNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANCELBY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CANCELREMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FLG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBARITEM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITEMCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ITEMDESCRIPTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOTID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOTNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KOTTIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MERGEKOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QUANTITY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("REMARKS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SPLITKOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TABLENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSFERKOT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WAITER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WAITERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KOT");
                });

            modelBuilder.Entity("SalesManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SalesManagement.Models.ProductIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ingredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductIngredients");
                });

            modelBuilder.Entity("SalesManagement.Models.ProductRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductRecipes");
                });

            modelBuilder.Entity("SalesManagement.Models.ProductRecipeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductIngredientId")
                        .HasColumnType("int");

                    b.Property<int>("ProductRecipeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductIngredientId");

                    b.HasIndex("ProductRecipeId");

                    b.ToTable("ProductRecipeDetails");
                });

            modelBuilder.Entity("SalesManagement.Models.SalesCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillToMob")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BillToPan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Cash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Complimentary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditCard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GVoucher")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Invoice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("NetSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Online")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OrderMode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Party")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Pax")
                        .HasColumnType("int");

                    b.Property<decimal>("STax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesReturnVoucher")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TRNTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TRNUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Invoice")
                        .IsUnique()
                        .HasDatabaseName("UQ_SalesCollection_Date_Invoice");

                    b.ToTable("SalesCollections");
                });

            modelBuilder.Entity("SalesManagement.Models.SalesDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BILLQTY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BSDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BaseQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BaseUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BillRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BillTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NetAmnt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonTaxable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("REFNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Salesman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TRNDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("TRNTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRNUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Taxable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Terminal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VCHRNO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Vat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TRNDATE", "VCHRNO", "ItemCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_SalesDetail_TRNDATE_VCHRNO_ITEMCODE")
                        .HasFilter("[VCHRNO] IS NOT NULL AND [ItemCode] IS NOT NULL");

                    b.ToTable("SalesDetail");
                });

            modelBuilder.Entity("SalesManagement.Models.ProductRecipe", b =>
                {
                    b.HasOne("SalesManagement.Models.CategoryRange", "CategoryRange")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagement.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryRange");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesManagement.Models.ProductRecipeDetail", b =>
                {
                    b.HasOne("SalesManagement.Models.ProductIngredient", "ProductIngredient")
                        .WithMany()
                        .HasForeignKey("ProductIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalesManagement.Models.ProductRecipe", "ProductRecipe")
                        .WithMany("Details")
                        .HasForeignKey("ProductRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductIngredient");

                    b.Navigation("ProductRecipe");
                });

            modelBuilder.Entity("SalesManagement.Models.ProductRecipe", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
